[workspace]
members = [
    "crates/juzo-macros",
    "crates/juzo-core",
    "crates/juzo",
]
resolver = "3"

[workspace.package]
edition = "2024"
publish = false

[patch.crates-io]
juzo-core = { path = "crates/juzo-core" }
juzo-macros = { path = "crates/juzo-macros" }

[workspace.dependencies]
tokio = { version = "1.52.1", features = ["full"] }
telers = { git = "https://github.com/Desiders/telers", rev = "9995b9666a1e5001e0c7ad2535d0db7908c3a0bc" }

# БД.
sea-orm = { version = "2.0.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-rust_decimal",
    "with-chrono",
] }

# Математика.
rust_decimal = "1.42.1"

# Время.
chrono = { version = "0.4.45", features = ["serde"] }
chrono-tz = "0.10.4"

